---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/tkn version --component client
    register: tkn_test_output
  - name: tkn version --component client
    debug:
      msg: '{{ tkn_test_output.stdout }}'
