---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install in {{ tkn_install_exe }}
  become: true
  stat:
    path: '{{ tkn_install_exe }}'
  changed_when: false
  register: tkn_binary
- when: not tkn_binary.stat.exists
  block:
    - name: downloading {{ tkn_url }} to {{ tkn_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ tkn_url }}'
        dest: '{{ tkn_tmp_archive }}'
        checksum: '{{ tkn_checksum }}'
        mode: 0644
    - name: mkdir {{ tkn_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ tkn_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ tkn_tmp_archive }} to {{ tkn_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ tkn_tmp_archive }}'
        dest: '{{ tkn_install_dir }}'
        creates: '{{ tkn_install_exe }}'
  always:
    - name: rm {{ tkn_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ tkn_tmp_archive }}'
        state: absent
- name: linking {{ tkn_install_exe }} to {{ tkn_install_link }}
  become: true
  become_user: root
  file:
    src: '{{ tkn_install_exe }}'
    dest: '{{ tkn_install_link }}'
    state: link
